In [1]:
from pathlib import Path
import numpy as np
import time

from astropy.io import fits
from astropy.nddata import CCDData

In [2]:
test_data_01 = np.ones((100, 100))
test_ccd_01 = CCDData(data=test_data_01, header=None, unit='adu')
print(type(test_ccd_01))
print(test_ccd_01.data)

<class 'astropy.nddata.ccddata.CCDData'>
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [3]:
test_ccd_01.header

OrderedDict()

In [4]:
test_ccd_01.write("test_01.fits", overwrite=True)

In [5]:
test_data_01 = np.ones((100, 100))
test_hdu_01 = fits.PrimaryHDU(data=test_data_01, header=None)
print(type(test_hdu_01))
print(test_hdu_01.data)

<class 'astropy.io.fits.hdu.image.PrimaryHDU'>
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [6]:
# If you want, you can make HDUList.
# But it is unnecessary because we have only one extension.
# hdul = fits.HDUList([test_hdu_01])

test_hdu_01.writeto("test_01.fits", overwrite=True, output_verify='fix')

In [7]:
test_ccd_01_read = CCDData.read("test_01.fits", unit="adu")
print(type(test_ccd_01_read))
print(test_ccd_01_read.data)

<class 'astropy.nddata.ccddata.CCDData'>
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [8]:
test_ccd_01_read.header

SIMPLE  =                    T / conforms to FITS standard                      
BITPIX  =                  -64 / array data type                                
NAXIS   =                    2 / number of array dimensions                     
NAXIS1  =                  100                                                  
NAXIS2  =                  100                                                  
EXTEND  =                    T                                                  

In [9]:
test_ccd_01_hdul = fits.open("test_01.fits")
print(type(test_ccd_01_hdul))

<class 'astropy.io.fits.hdu.hdulist.HDUList'>


In [10]:
print(test_ccd_01_hdul.info())

Filename: test_01.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU       6   (100, 100)   float64   


None


In [11]:
print(type(test_ccd_01_hdul[0]))
print(type(test_ccd_01_hdul["PRIMARY"]))

<class 'astropy.io.fits.hdu.image.PrimaryHDU'>
<class 'astropy.io.fits.hdu.image.PrimaryHDU'>


In [12]:
print(test_ccd_01_hdul[0].data)

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [13]:
test_ccd_01_hdul[0].header

SIMPLE  =                    T / conforms to FITS standard                      
BITPIX  =                  -64 / array data type                                
NAXIS   =                    2 / number of array dimensions                     
NAXIS1  =                  100                                                  
NAXIS2  =                  100                                                  
EXTEND  =                    T                                                  

In [14]:
test_data_02 = np.ones((10, 20))

header_str = '''OBJECT  = 'dark    '                                                            
GAIN    =    1.360000014305115 / [e-/ADU] The electron gain factor.             
RDNOISE =                  9.0 / [e-] The (Gaussian) read noise.                
'''
header = fits.Header.fromstring(header_str, sep='\n')
test_ccd_02 = CCDData(data=test_data_02, header=header, unit='adu')

In [15]:
test_ccd_02.header

OBJECT  = 'dark    '                                                            
GAIN    =    1.360000014305115 / [e-/ADU] The electron gain factor.             
RDNOISE =                  9.0 / [e-] The (Gaussian) read noise.                

In [16]:
test_ccd_02.write("test2.fits", overwrite=True)
test_ccd_02_read = CCDData.read("test2.fits")

In [17]:
test_ccd_02_read.header

SIMPLE  =                    T / conforms to FITS standard                      
BITPIX  =                  -64 / array data type                                
NAXIS   =                    2 / number of array dimensions                     
NAXIS1  =                   20                                                  
NAXIS2  =                   10                                                  
OBJECT  = 'dark    '                                                            
GAIN    =    1.360000014305115 / [e-/ADU] The electron gain factor.             
RDNOISE =                  9.0 / [e-] The (Gaussian) read noise.                
BUNIT   = 'adu     '                                                            

In [18]:
header = fits.Header.fromstring('')  # empty header

# 1) Basic setting
header["object"] = 'dark'  # header key will automatically be capitalized

# 2) With comment
header["GAIN"] = (1.36, "[e-/ADU] The electron gain factor.")

# 3) Using .set()
header.set("RDNOISE", 9.0, "[e-] The (Gaussian) read noise.")
header.set("RDNOISE", 10.0, "[e-] The (Gaussian) read noise. Oops, I am adding it again! What will happen?")

# 4) Adding COMMENT line
header.add_comment("This is a testing fits file.")
header.add_comment("This is the second comment.")
header.add_comment("What if the comment is too long? "*6)

# 5) Adding HISTORY line
header.add_history("Bias subtracted 2019-01-01T00:00:01")
header.add_history("Dark corrected 2019-01-01T00:00:02")
header.add_history("Flat corrected 2019-01-01T00:00:03")
header.add_history("Cosmic ray rejected 2019-01-01T00:00:04")
header.add_history("WCS added 2019-01-01T00:00:06")

test_ccd_03 = CCDData(data=test_data_02, header=header, unit='adu')

In [19]:
test_ccd_03.header

OBJECT  = 'dark    '                                                            
GAIN    =                 1.36 / [e-/ADU] The electron gain factor.             
RDNOISE =                 10.0 / [e-] The (Gaussian) read noise. Oops, I am addi
COMMENT This is a testing fits file.                                            
COMMENT This is the second comment.                                             
COMMENT What if the comment is too long? What if the comment is too long? What i
COMMENT f the comment is too long? What if the comment is too long? What if the 
COMMENT comment is too long? What if the comment is too long?                   
HISTORY Bias subtracted 2019-01-01T00:00:01                                     
HISTORY Dark corrected 2019-01-01T00:00:02                                      
HISTORY Flat corrected 2019-01-01T00:00:03                                      
HISTORY Cosmic ray rejected 2019-01-01T00:00:04                                 
HISTORY WCS added 2019-01-01

In [20]:
test_ccd_03.write("test3.fits", overwrite=True)
test_ccd_03_read = CCDData.read("test3.fits")

In [21]:
test_ccd_03_read.header

SIMPLE  =                    T / conforms to FITS standard                      
BITPIX  =                  -64 / array data type                                
NAXIS   =                    2 / number of array dimensions                     
NAXIS1  =                   20                                                  
NAXIS2  =                   10                                                  
OBJECT  = 'dark    '                                                            
GAIN    =                 1.36 / [e-/ADU] The electron gain factor.             
RDNOISE =                 10.0 / [e-] The (Gaussian) read noise. Oops, I am addi
BUNIT   = 'adu     '                                                            
COMMENT This is a testing fits file.                                            
COMMENT This is the second comment.                                             
COMMENT What if the comment is too long? What if the comment is too long? What i
COMMENT f the comment is too

In [22]:
prim = fits.PrimaryHDU(data=None, header=header)
im1 = fits.ImageHDU(data=np.ones((10, 10)), header=None, name="SCI")
im2 = fits.ImageHDU(data=np.zeros((10, 10)), header=None, name="UNCERT")
hdul_mef = fits.HDUList([prim, im1, im2])
hdul_mef.writeto("test_mef.fits", overwrite=True, output_verify='fix')

In [23]:
hdul_mef_read = fits.open("test_mef.fits")
print(hdul_mef_read.info())

Filename: test_mef.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU      17   ()      
  1  SCI           1 ImageHDU         8   (10, 10)   float64   
  2  UNCERT        1 ImageHDU         8   (10, 10)   float64   


None


In [24]:
np.testing.assert_allclose(hdul_mef_read[1].data, hdul_mef_read["SCI"].data)

In [25]:
hdul_mef_data_1 = fits.getdata("test_mef.fits", ext=1)
hdul_mef_data_2 = fits.getdata("test_mef.fits", extname="UNCERT")
np.testing.assert_allclose(hdul_mef_data_1, hdul_mef_data_1 - hdul_mef_data_2)

In [26]:
test_ccd_mef_read = CCDData.read("test_mef.fits", unit='adu')

INFO: first HDU with data is extension 1. [astropy.nddata.ccddata]


In [27]:
test_ccd_mef_read.data

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [28]:
print(type(test_ccd_mef_read.uncertainty))
test_ccd_mef_read.uncertainty

<class 'astropy.nddata.nduncertainty.StdDevUncertainty'>


StdDevUncertainty([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
                   [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
                   [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
                   [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
                   [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
                   [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
                   [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
                   [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
                   [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
                   [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
tmpfitsfiles = Path('.').glob("test*.fits")
for fpath in tmpfitsfiles:
    fpath.unlink()